name: Check Python codes typing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  typing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11

    - name: Set up Poetry 1.2.2
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: 1.2.2

    - name: Set up dependencies cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        poetry config virtualenvs.create false
        poetry install

    - name: Check typing with pyright
      uses: jakebailey/pyright-action@v1
